apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    uid: GhzMNppVk
    url: postgres:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: 'secretpassword'
    jsonData:
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
